##
## EPITECH PROJECT, 2019
## solostumper_3
## File description:
## Makefile
##

SRCS = 	main.c

NAME = fozzbazz

all : ${NAME}

CFLAGS += -W -Wall -Wextra

${NAME} :
	gcc -o ${NAME} ${SRCS}

clean :
	rm ${NAME}

fclean : clean

re : clean fclean all
